version: '3.8'

services:
  web:
    build: .
    
    command: python manage.py runserver 0.0.0.0:8000 --settings=assessme.settings.dev
    volumes:
      - .:/myapp
      
    ports:
      - "8000:8000"
    env_file:
    - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=assessme
      - POSTGRES_PASSWORD=assessme
      - POSTGRES_DB=assessme
volumes:
  postgres_data:
